name: televerse_shelf
description: Helps you build fully customizable web servers using Shelf while managing your bot's webhook on a dedicated route.
version: 1.0.0
homepage: https://televerse.xooniverse.com
repository: https://github.com/xooniverse/televerse_shelf

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  televerse: ^2.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  shelf_router: ^1.1.0

topics:
  - telegram
  - bot
  - chat
  - telegram-bot-api
  - bot-framework

funding:
  - https://buymeacoffee.com/heysreelal
  - https://paypal.me/sreelalts